### ISSUE TITLE
Audio out option -o alsa

### ISSUE THREAD

**Issue by warkanum** [brainfoolong/omxwebgui-v2#10]
Hi.

Alsa audio output was required. Local didn't work. 
So I added an ALSA option on Audio out device in /src/View/Settings.php
The added option allows for omxplayer -b -o alsa ...
Thanks for this great tool.

**Comment by brainfoolong** [comment]
Thanks, would be nice if you can make a pull request.

**Comment by warkanum** [comment]
All done.

**Comment by brainfoolong** [comment]
Thanks 👍  Merged, closed
