### ISSUE TITLE
Folder name is never shown even if "hidefolder" setting is deactivated

### ISSUE THREAD

**Issue by ptaferner** [brainfoolong/omxwebgui-v2#18]
The folder names on the file list are never shown, no matter what the settings are.
I could already identify the bug:
In index js on line 145 the user setting is checked. However, if "hidefolder" is deactivated, the value of this setting is "0", so the string "0". In Javascript, "0" evaluates to true, if a type conversion to Boolean is done.

**Comment by brainfoolong** [comment]
Correcto, i'll fix this. Thanks for notice.

**Comment by brainfoolong** [comment]
Well, fixed in 0.12.1.
