### ISSUE TITLE
Recursive directory listing only one level deep

### ISSUE THREAD

**Issue by lowercasename** [brainfoolong/omxwebgui-v2#20]
This is an amazing and slick tool, thank you for all your work on it! I've been really enjoying it. One issue I've found is that when the recursive option is turned on, the directory listing only seems to descend one directory level down. Folders within folders don't appear to be indexed. Is this some sort of permissions problem I haven't tested enough, or a problem with the GUI?

**Comment by brainfoolong** [comment]
Hi, and thanks. It should work with unlimited depth. I use it for myself and i have it with multiple depths and it works fine. Maybe permission problems or no suopprted video files in the depth folders?

**Comment by lowercasename** [comment]
...you're completely right, there were no valid video files in those folders. Sorry!

**Comment by brainfoolong** [comment]
No problem. Have a nice weekend.
