### ISSUE TITLE
No way to stop omxplayer after playing multiple files simulatenously

### ISSUE THREAD

**Issue by lowercasename** [brainfoolong/omxwebgui-v2#21]
This is the other issue I've noticed, and I'm _sure_ this one isn't my mistake! 👀 

If, say, I clumsily click two files one after the other without stopping the first one first, I can then control the second file, but none of the keybindings do anything to stop the original file. I have to ssh into my Pi, pkill omxplayer, then reboot. Is there any way to automatically force the original file to stop playing?

**Comment by brainfoolong** [comment]
Normally the script does kill all existing omxplayer instances whenever you play a new file. Maybe, if you do this multiple times when the other processes aren't done yet, it could be possible to create a mess. But this should be fixed when you wait a few seconds and that click again on the video you want to play.

It should kill all omxplayers and start fine with the new one.

**Comment by brainfoolong** [comment]
This is related to https://github.com/brainfoolong/omxwebgui-v2/issues/23#issuecomment-346256727 - It'
s a problem with DBUS System that is used implicit by omxplayer and of what i have no real control of.
