### ISSUE TITLE
Failed to listen on 0.0.0.0:4321 (reason: Address already in use)

### ISSUE THREAD

**Issue by fkbreitl** [brainfoolong/omxwebgui-v2#22]
When omxwebgui has played files and is restarted the error `Failed to listen on 0.0.0.0:4321 (reason: Address already in use)` appears.

It is caused by the dbus-daemon that is still running.
It would be nice if this problem could be avoided somehow.

**Comment by brainfoolong** [comment]
I will build a wrapper script to start/stop the server. It than can be used with something like `./omxwebgui start-server|stop-server`

**Comment by brainfoolong** [comment]
Merged into https://github.com/brainfoolong/omxwebgui-v2/issues/23
