### ISSUE TITLE
Output too verbose for useful logging

### ISSUE THREAD

**Issue by fkbreitl** [brainfoolong/omxwebgui-v2#24]
A `/var/log/omxwebgui.log` file as suggested in #23 could be very helpful for finding problems.

Unfortunately omxwebgui is currently too verbose for a meaningful logging since it creates a meaningless entry almost every second which looks like

`[Tue Nov 21 21:32:16 2017] 192.168.178.20:54145 [200]: /index.php/index`.

Could these lines be removed?

**Comment by brainfoolong** [comment]
The output cannot be changed. It's the default from PHP's built in webserver. It's the access log.
