### ISSUE TITLE
Stream start at 2X speed

### ISSUE THREAD

**Issue by arvjsr1802** [brainfoolong/omxwebgui-v2#26]
While playing RTMP streams, it auto start with 2X speed

**Comment by brainfoolong** [comment]
Just see this -> https://github.com/brainfoolong/omxwebgui-v2/issues/6

Settings -> Double speed fix

**Comment by arvjsr1802** [comment]
Unable to find #6 , please send a link

**Comment by arvjsr1802** [comment]
UDP stream automatically stops after 15 minutes.

**Comment by brainfoolong** [comment]
This UDP stream problem is omxplayer related, i cannot fix anything here.
