### ISSUE TITLE
URL mapping fails when used with nginx

### ISSUE THREAD

**Issue by robmint** [brainfoolong/omxwebgui-v2#3]
I'm running omxwebgui-v2 with nginx because I have another web interface that i'd like to co-exist with omxwebgui.

When I go to a URL like `http://127.0.0.1/player/index.php/settings` I get 404. Is there a rewrite rule I can add to make that work?

**Comment by robmint** [comment]
I found this config worked:
```
	location ~ [^/]\.php(/|$) {
		include snippets/fastcgi-php.conf;
		fastcgi_split_path_info ^(.+?\.php)(/.*)$;
	    if (!-f $document_root$fastcgi_script_name) {
		return 404;
	    }
		fastcgi_pass unix:/var/run/php5-fpm.sock;
	}
```

**Comment by brainfoolong** [comment]
Ok, thx for letting me know.
