### ISSUE TITLE
How to change video resolution from HD to SD and vice versa

### ISSUE THREAD

**Issue by arvjsr1802** [brainfoolong/omxwebgui-v2#30]
Hi,

Please help me to change video resolution from HD to SD and vice versa.

**Comment by brainfoolong** [comment]
Hi, it is not possible with this tool.

**Comment by arvjsr1802** [comment]
Can you please suggest me tool if you are aware ?

**Comment by brainfoolong** [comment]
I have no suggestion, sorry.
