### ISSUE TITLE
Problems if you don't stop a video before selecting a new one

### ISSUE THREAD

**Issue by robmint** [brainfoolong/omxwebgui-v2#4]
If you play a video, then select another video, the UI correctly displays the name of the new video and says "Playing". But the old video continues to play.

Perhaps the UI needs to send the "Stop" command to omxplayer before starting to play a new video. If you do this manually it works OK.

**Comment by brainfoolong** [comment]
I guess you using this all with nginx? There a problems when you using this gui not in the recommended way via the php command line. As you can see in the following file, on every video start, it will already kill all omxplayer instances. The problem you describe doesn't happen on all my tested instances.

https://github.com/brainfoolong/omxwebgui-v2/blob/master/omx-start.sh
