### ISSUE TITLE
Loop options / sequential playlist

### ISSUE THREAD

**Issue by VoTomas** [brainfoolong/omxwebgui-v2#5]
Hi, 

first of all great job on the script: :) 

Second am I missing something or does the interface lack two options I see as very important for players;

1) To play files that are in the playlist sequentially (for me it just stops after one file). 

2) Have options for loop / repeat one / playlist, etc. as most other players do

Am I missing something or is it not implemented? :) 

Thanks!

**Comment by brainfoolong** [comment]
Thanks.
Well, that 2 things are not that easy tasks to do with that interface.
It requires a complete wrapper over omx to make those things working.
Some sort of "when stopped do this". Currently, there is no way to do this easily.
It will require a lot of rework to this interface. Maybe i can do this someday, but for now, i'm sorry.

**Comment by VoTomas** [comment]
Easy does it, no need to apologize. :)
