### ISSUE TITLE
Playspeed 2x when playing a video

### ISSUE THREAD

**Issue by eliperel** [brainfoolong/omxwebgui-v2#6]
When playing a video, it automatically starts at Playspeed 2x
I'm using version 0.10.10.

Workaround:
-Speed down
-Speed Up (now at 1x)

**Comment by brainfoolong** [comment]
Just enable double  speed fix in the settings.

Am 14.01.2017 10:54 Nachm. schrieb "eliperel" <notifications@github.com>:
