### ISSUE TITLE
Search function not working for second configured directory

### ISSUE THREAD

**Issue by casu** [brainfoolong/omxwebgui-v2#7]
Thanks for your great project. On my Pi I cannot find video files in the second configured directory. Files in the first directory will bei found as expected.

**Comment by brainfoolong** [comment]
Maybe you've a typo in your path? I've tested it right now also on my pi with multiple folders, work like a charm.

**Comment by casu** [comment]
I played around now a little bit and can give some more information. 

On a second raspi I made a fresh install of raspbian and configured two directories with mp4 files. 
/home/pi/Downloads/
/home/pi/Videos/
I can search for files in both directories. Works like expected.

On my other raspi I have an external USB HDD mounted under /media/USB300GB/ where a lot of mp4s are located under /data/video/.

I configured:
/home/pi/Downloads/
/media/USB300GB/data/video/
/home/pi/Videos/

The search function finds files under the first directory but cannot find files in the other two directories.

If I change the order to
/home/pi/Downloads/
/home/pi/Videos/
/media/USB300GB/data/video/

Now I'm able to find files in the first two directories. It seems it has something to do with the mounted drive.

Conclusion: All files are displayed in the file list but the search function does not find files on the external drive and all directories behind that drive.

Strange.

**Comment by casu** [comment]
Additional remark: All files are displayed in the file list but the search function does not find files on the external drive and all directories behind that mount point.

**Comment by brainfoolong** [comment]
Does that mean that really all expected files are in the list when you scroll down, but when you search they are not found? Maybe your mounted drive has unsupported chars in in it. Some logs in the F12 console of your browser, when you do the search?

**Comment by casu** [comment]
Hi!

I found the problem. On the hard drive was one file with wrong displayed "Umlaut".

DerTatortreiniger-?zg?r.mp4

This results in a entry in the file list named "null".

I renamed the file in a correct file name

DerTatortreiniger-Oezguer.mp4

and now all displayed files can be found via search function.

And yes all files were displayed in the file list.

**Comment by brainfoolong** [comment]
Ok, than i know where to search for the bug. Thx.

**Comment by brainfoolong** [comment]
I tried to reproduce this bug with a few very wrong encoded filenames. Not possible to reproduce this bug. I have tested this with USB drives and network drives, both work like a charm also with special chars and stuff like that. I close this, maybe i have to reopen it sometimes.
