### ISSUE TITLE
Loop, next and previous Clip at the Shortcuts. Gpi in for play

### ISSUE THREAD

**Issue by JulosTV** [brainfoolong/omxwebgui-v2#8]
Hi, your project ist amazing. I want to use it with my visionmixer as mediaplayer besides the cameras.
I already managed to loop a video without onscreen display (omxplayer --loop --....).
Is it possible to put something like this in your Remote Page? Also next and previous Clip would be wonderful.

The integration of GPI in would be great. When I Press a Button the Video Starts to Play... So I could combine it with mY arduino which controls my visionmixer. 
Example: when I switch the Mediaplayer on air, the Player automaticly Starts to Play.

Thanks in advance!!
Julian

**Comment by brainfoolong** [comment]
Sounds like an interesting thing but unfortunetely it is nothing that i can do for you. It is too specific to your case to implement it in this repository. Feel free to modifiy it to your needs, but i can't help here, sorry. For some GPIO processing and a good starting point for you, i have also another library, also based on PHP. https://github.com/brainfoolong/gpio-webinterface. So, you maybe can combine both things to your needs. Both are *relatively* simple code. When you dig into the code, i'm sure you can do it yourself.
